import { useEffect, useMemo, useState, type Dispatch, type SetStateAction } from 'react'
import { ChallengePanel, type ChallengeReward } from './components/ChallengePanel'
import { CommunityBoard } from './components/CommunityBoard'
import { TeamPanel } from './components/TeamPanel'
import { getRound, questions, sessionPresets } from './data/content'
import { getStrings } from './data/strings'
import { readStored, removeStored, writeStored } from './hooks/useLocalStorage'
import { useSound } from './hooks/useSound'
import { useTimer } from './hooks/useTimer'
import { selectUnusedQuestion } from './game/questionManager'
import type { ChallengeType, GameMode, GameSettings, GameState, SessionLength, TeamId, TeamState, TokenType } from './game/types'

const SETTINGS_KEY = 'value-of-work-settings'
const GAME_KEY = 'value-of-work-game'
const REPORT_KEY = 'value-of-work-last-report'
const REFLECTION_KEY = 'value-of-work-reflection'
const defaultSettings: GameSettings = { timerEnabled: true, soundEnabled: false, reducedMotion: false, readingMode: 'standard', language: 'en' }

function makeTeam(id: TeamId, name: string): TeamState { return { id, name, score: 0, contributions: 0, tokens: { work: 0, skill: 0, connection: 0, cooperation: 0, community: 0 } } }
function toggleTeam(team: TeamId): TeamId { return team === 'A' ? 'B' : 'A' }

function newGame(settings: GameSettings, mode: GameMode = 'teams', sessionLength: SessionLength = 'full', names?: [string, string]): GameState {
  const defaults = mode === 'teams' ? ['The Contributors', 'The Community Builders'] : ['Player A', 'Player B']
  return { screen: 'home', mode, sessionLength, activeRounds: sessionPresets[sessionLength].rounds, sessionSeed: Date.now() % 10000, teams: { A: makeTeam('A', names?.[0] || defaults[0]), B: makeTeam('B', names?.[1] || defaults[1]) }, activeTeam: 'A', currentRound: 0, usedQuestionIds: [], completedChallenges: [], discoveredWork: [], completedChains: 0, predictions: 0, problemsSolved: 0, hiddenWorkDiscovered: 0, recognitions: [], challengeHistory: [], settings }
}

function normalizeGame(saved: GameState): GameState {
  const sessionLength = saved.sessionLength || 'full'
  return { ...newGame({ ...defaultSettings, ...saved.settings }, saved.mode || 'teams', sessionLength, [saved.teams?.A?.name || 'The Contributors', saved.teams?.B?.name || 'The Community Builders']), ...saved, sessionLength, activeRounds: saved.activeRounds?.length ? saved.activeRounds : sessionPresets[sessionLength].rounds, recognitions: saved.recognitions || [], challengeHistory: saved.challengeHistory || [] }
}

function TokenLegend() { return <div className="token-legend" aria-label="Token legend"><span>✦ Work</span><span>◆ Skill</span><span>⛓ Connection</span><span>♧ Cooperation</span><span>♥ Community</span></div> }

function Home({ onNew, onContinue, hasSaved }: { onNew: () => void; onContinue: () => void; hasSaved: boolean }) {
  return <main className="home-screen"><div className="home-glow glow-one" /><div className="home-glow glow-two" /><section className="intro-card"><div className="chapter-marker"><span>13</span> Grade 6 • Social Science</div><p className="eyebrow">Community challenge</p><h1>The Value <em>of Work</em></h1><p className="intro-copy">Every community depends on many kinds of work. Discover the connections, test what happens when one link stops, and restore the community together.</p><div className="intro-actions"><button type="button" className="primary-action large" onClick={onNew}>Start challenge <span aria-hidden="true">→</span></button>{hasSaved && <button type="button" className="secondary-action" onClick={onContinue}>Continue saved game</button>}</div><TokenLegend /></section><section className="intro-board" aria-label="Miniature community preview"><div className="mini-sun" aria-hidden="true">☀</div><div className="mini-cloud cloud-one" aria-hidden="true" /><div className="mini-cloud cloud-two" aria-hidden="true" /><div className="mini-location farm"><span>🌱</span><b>Farm</b></div><div className="mini-location workshop"><span>🛠</span><b>Workshop</b></div><div className="mini-location market"><span>🧺</span><b>Market</b></div><div className="mini-location school"><span>✏️</span><b>School</b></div><div className="mini-location hospital"><span>✚</span><b>Hospital</b></div><div className="mini-location community"><span>🏘</span><b>Community</b></div><svg viewBox="0 0 700 380" preserveAspectRatio="none" aria-hidden="true"><path d="M108 170 C225 100 282 175 347 190 S498 155 580 210" /><path d="M348 190 C460 290 515 286 575 280" /></svg><div className="intro-message"><span aria-hidden="true">✦</span><p>Many kinds of work<br /><b>help a community function.</b></p></div></section></main>
}

function Setup({ game, setGame, onStart }: { game: GameState; setGame: Dispatch<SetStateAction<GameState>>; onStart: () => void }) {
  const setMode = (mode: GameMode) => setGame(current => newGame(current.settings, mode, current.sessionLength))
  const setSession = (sessionLength: SessionLength) => setGame(current => ({ ...current, sessionLength, activeRounds: sessionPresets[sessionLength].rounds }))
  const updateName = (team: TeamId, name: string) => setGame(current => ({ ...current, teams: { ...current.teams, [team]: { ...current.teams[team], name } } }))
  return <main className="setup-screen"><section className="setup-card"><div className="chapter-marker"><span>13</span> Community Challenge</div><p className="eyebrow">Choose your play mode</p><h1>Build a better community <em>together.</em></h1><div className="mode-switch" role="group" aria-label="Game mode"><button type="button" className={game.mode === 'teams' ? 'selected' : ''} onClick={() => setMode('teams')}><span>♟</span><b>Two team mode</b><small>Perfect for a classroom</small></button><button type="button" className={game.mode === 'players' ? 'selected' : ''} onClick={() => setMode('players')}><span>⚉</span><b>Two player mode</b><small>Play head-to-head</small></button></div><div className="session-picker" role="group" aria-label="Session length">{(Object.keys(sessionPresets) as SessionLength[]).map(length => <button type="button" key={length} className={game.sessionLength === length ? 'selected' : ''} onClick={() => setSession(length)}><b>{sessionPresets[length].label}</b><small>{sessionPresets[length].description}</small><span>{sessionPresets[length].rounds.length} rounds</span></button>)}</div><div className="name-fields"><label><span>{game.mode === 'teams' ? 'Team A name' : 'Player A name'}</span><input value={game.teams.A.name} maxLength={28} onChange={event => updateName('A', event.target.value)} /></label><span className="versus">VS</span><label><span>{game.mode === 'teams' ? 'Team B name' : 'Player B name'}</span><input value={game.teams.B.name} maxLength={28} onChange={event => updateName('B', event.target.value)} /></label></div><p className="setup-note">{sessionPresets[game.sessionLength].description} Take turns, build connections, and collect contribution tokens.</p><button type="button" className="primary-action large" onClick={onStart}>Ready — start game <span aria-hidden="true">→</span></button></section></main>
}

interface TeacherControlsProps { settings: GameSettings; teams: Record<TeamId, TeamState>; rounds: ReturnType<typeof getRound>[]; currentRound: number; timerPaused: boolean; onSettings: (key: keyof GameSettings, value?: string | boolean) => void; onReset: () => void; onRestart: () => void; onSkip: () => void; onChooseRound: (round: number) => void; onPause: () => void; onFullscreen: () => void; onRename: (team: TeamId, name: string) => void }
function TeacherControls({ settings, teams, rounds, currentRound, timerPaused, onSettings, onReset, onRestart, onSkip, onChooseRound, onPause, onFullscreen, onRename }: TeacherControlsProps) {
  const words = getStrings(settings.language)
  return <details className="teacher-controls"><summary>{words.teacherControls} <span aria-hidden="true">⚙</span></summary><div><label><input aria-label="Timer enabled" type="checkbox" checked={settings.timerEnabled} onChange={() => onSettings('timerEnabled')} /> Timer enabled</label><button type="button" aria-label={timerPaused ? words.resume : words.pause} onClick={onPause}>{timerPaused ? words.resume : words.pause}</button><label><input aria-label="Sound feedback" type="checkbox" checked={settings.soundEnabled} onChange={() => onSettings('soundEnabled')} /> Sound feedback</label><label><input aria-label="Reduced motion" type="checkbox" checked={settings.reducedMotion} onChange={() => onSettings('reducedMotion')} /> Reduced motion</label><label><input aria-label="Focus reading mode" type="checkbox" checked={settings.readingMode === 'focus'} onChange={() => onSettings('readingMode', settings.readingMode === 'focus' ? 'standard' : 'focus')} /> Focus reading mode</label><label className="round-select"><span>Language-ready UI</span><select aria-label="Choose interface language" value={settings.language} onChange={event => onSettings('language', event.target.value)}><option value="en">English</option><option value="hi">हिन्दी UI</option></select></label><label className="round-select"><span>Jump to round</span><select aria-label="Jump to round" value={currentRound} onChange={event => onChooseRound(Number(event.target.value))}>{rounds.map((round, index) => <option key={round.type} value={index}>{index + 1}. {round.title}</option>)}</select></label><label className="team-rename"><span>Rename teams</span><input aria-label="Rename Team A" value={teams.A.name} onChange={event => onRename('A', event.target.value)} /><input aria-label="Rename Team B" value={teams.B.name} onChange={event => onRename('B', event.target.value)} /></label><button type="button" aria-label={words.fullscreen} onClick={onFullscreen}>{words.fullscreen}</button><button type="button" aria-label="Restart current round" onClick={onRestart}>Restart current round</button><button type="button" aria-label="Skip this round" onClick={onSkip}>Skip this round</button><button type="button" aria-label={words.newGame} onClick={onReset}>{words.newGame}</button></div></details>
}

function RewardCard({ reward, round, lastRound, onNext }: { reward: ChallengeReward; round: ReturnType<typeof getRound>; lastRound: boolean; onNext: () => void }) {
  return <section className="reward-card" aria-live="polite"><div className="reward-burst" aria-hidden="true">✦</div><p className="eyebrow">Contribution collected</p><h2>{lastRound ? 'Community restored!' : 'Great connection!'}</h2><p>{reward.message}</p><div className="reward-numbers"><b>+{reward.points} points</b><span>+1 {reward.token} token</span></div>{reward.recognition && <span className="recognition-chip">★ {reward.recognition}</span>}<div className="learning-card"><b>Why this matters</b><p>{round.takeaway}</p><small>Discuss: {round.discussion}</small></div><button type="button" className="primary-action" onClick={onNext}>{lastRound ? 'View community report' : 'Pass turn & continue'} <span aria-hidden="true">→</span></button></section>
}

function GameView({ game, setGame, onResults }: { game: GameState; setGame: Dispatch<SetStateAction<GameState>>; onResults: () => void }) {
  const [roundComplete, setRoundComplete] = useState(false); const [lastReward, setLastReward] = useState<ChallengeReward | null>(null); const [selectedLocation, setSelectedLocation] = useState<string | null>(null); const [rippleNodes, setRippleNodes] = useState<string[]>([]); const [travel, setTravel] = useState<{ item: string; nodes: string[]; nonce: number } | null>(null); const [timerPaused, setTimerPaused] = useState(false); const [challengeVersion, setChallengeVersion] = useState(0)
  const sessionRounds = game.activeRounds.map(getRound); const round = sessionRounds[game.currentRound]; const activeTeam = game.teams[game.activeTeam]; const otherTeam = game.teams[toggleTeam(game.activeTeam)]; const playSound = useSound(game.settings.soundEnabled)
  const question = useMemo(() => selectUnusedQuestion(questions, game.usedQuestionIds, round.questionCategory, game.sessionSeed + game.currentRound + challengeVersion) || questions[0], [game.usedQuestionIds, game.currentRound, game.sessionSeed, round.questionCategory, challengeVersion])
  const seconds = useTimer(round.time, game.settings.timerEnabled && !timerPaused && !roundComplete, `${game.currentRound}-${challengeVersion}`)
  useEffect(() => { setRoundComplete(false); setLastReward(null); setRippleNodes([]); setTravel(null); setTimerPaused(false) }, [game.currentRound, round.time])
  useEffect(() => { if (seconds === 5 && game.settings.timerEnabled && !timerPaused) playSound('warning') }, [seconds, game.settings.timerEnabled, playSound, timerPaused])
  const complete = (reward: ChallengeReward) => { const recipient = reward.teamId || game.activeTeam; setGame(current => { const team = current.teams[recipient]; const tokens = { ...team.tokens, [reward.token]: team.tokens[reward.token] + 1 }; return { ...current, teams: { ...current.teams, [recipient]: { ...team, score: team.score + reward.points, contributions: team.contributions + 1, tokens } }, usedQuestionIds: round.type === 'quiz' ? [...new Set([...current.usedQuestionIds, question.id])] : current.usedQuestionIds, completedChallenges: [...current.completedChallenges, round.type], challengeHistory: [...current.challengeHistory, round.type], discoveredWork: [...new Set([...current.discoveredWork, ...(reward.discovered || [])])], completedChains: current.completedChains + (reward.chains || 0), predictions: current.predictions + (reward.predictions || 0), problemsSolved: current.problemsSolved + (reward.problems || 0), hiddenWorkDiscovered: current.hiddenWorkDiscovered + (reward.hiddenWork || 0), recognitions: reward.recognition ? [...new Set([...current.recognitions, reward.recognition])] : current.recognitions } }); setLastReward(reward); setRoundComplete(true); playSound(round.type === 'crisis' ? 'restore' : 'reward') }
  const nextRound = () => { if (game.currentRound === sessionRounds.length - 1) { onResults(); return } setGame(current => ({ ...current, activeTeam: toggleTeam(current.activeTeam), currentRound: current.currentRound + 1 })) }
  const updateSetting = (key: keyof GameSettings, value?: string | boolean) => setGame(current => ({ ...current, settings: { ...current.settings, [key]: value ?? !current.settings[key] } }))
  const reset = () => setGame(current => ({ ...newGame(current.settings, current.mode, current.sessionLength, [current.teams.A.name, current.teams.B.name]), screen: 'setup' }))
  const restart = () => { setRoundComplete(false); setLastReward(null); setRippleNodes([]); setTravel(null); setTimerPaused(false); setChallengeVersion(current => current + 1) }
  const chooseRound = (roundIndex: number) => roundIndex === game.currentRound ? restart() : setGame(current => ({ ...current, currentRound: roundIndex, activeTeam: roundIndex % 2 === 0 ? 'A' : 'B' }))
  const fullscreen = () => { if (document.fullscreenElement) void document.exitFullscreen(); else void document.documentElement.requestFullscreen?.() }
  const rename = (team: TeamId, name: string) => setGame(current => ({ ...current, teams: { ...current.teams, [team]: { ...current.teams[team], name } } }))
  const startTravel = (item: string, nodes: string[]) => { setTravel({ item, nodes, nonce: Date.now() }); playSound('select'); window.setTimeout(() => setTravel(null), 2800) }
  const startRipple = (nodes: string[]) => { setRippleNodes(nodes); playSound('select') }
  return <main className={`game-screen ${game.settings.reducedMotion ? 'reduce-motion' : ''} ${game.settings.readingMode === 'focus' ? 'focus-reading' : ''}`}><a className="skip-link" href="#challenge">Skip to current challenge</a><header className="game-header"><div className="brand"><span className="brand-mark" aria-hidden="true">✦</span><div><p>Chapter 13</p><h1>The Value of Work</h1></div></div><div className="objective"><span aria-hidden="true">♧</span><p><b>Current objective</b><br />Discover how work keeps a community connected.</p></div><div className="game-tools"><div className={`timer ${seconds <= 5 && game.settings.timerEnabled ? 'warning' : ''}`}><span aria-hidden="true">◷</span><b>{game.settings.timerEnabled ? `${seconds}s` : 'Timer off'}</b></div><TeacherControls settings={game.settings} teams={game.teams} rounds={sessionRounds} currentRound={game.currentRound} timerPaused={timerPaused} onSettings={updateSetting} onReset={reset} onRestart={restart} onSkip={nextRound} onChooseRound={chooseRound} onPause={() => setTimerPaused(current => !current)} onFullscreen={fullscreen} onRename={rename} /></div></header><div className="round-ribbon" aria-label={`Round ${game.currentRound + 1} of ${sessionRounds.length}`}><span className="round-count">{sessionPresets[game.sessionLength].label} · {game.currentRound + 1} / {sessionRounds.length}</span>{sessionRounds.map((item, index) => <span key={`${item.type}-${index}`} className={`round-dot ${index === game.currentRound ? 'current' : ''} ${index < game.currentRound ? 'done' : ''}`} title={item.title}><i>{item.icon}</i><b>{item.title}</b></span>)}</div><div className="game-layout"><TeamPanel team={game.teams.A} active={game.activeTeam === 'A'} side="left" /><section className="center-stage"><div className="turn-banner"><span>{activeTeam.name}'s turn</span><p>{round.kicker}</p></div><CommunityBoard completed={game.completedChallenges.length} selected={selectedLocation} onSelect={setSelectedLocation} rippleNodes={rippleNodes} travel={travel} reducedMotion={game.settings.reducedMotion} /><div id="challenge" className="challenge-slot">{roundComplete && lastReward ? <RewardCard reward={lastReward} round={round} lastRound={game.currentRound === sessionRounds.length - 1} onNext={nextRound} /> : <ChallengePanel key={`${round.type}-${game.currentRound}-${challengeVersion}`} type={round.type} activeTeamName={activeTeam.name} stealTeamName={otherTeam.name} stealTeamId={otherTeam.id} question={question} variantSeed={game.sessionSeed + game.currentRound * 11 + challengeVersion} onComplete={complete} onRipple={startRipple} onTravel={startTravel} />}</div></section><TeamPanel team={game.teams.B} active={game.activeTeam === 'B'} side="right" /></div></main>
}

function Results({ game, onNew }: { game: GameState; onNew: () => void }) {
  const [reflection, setReflection] = useState<string[]>(() => readStored<string[]>(REFLECTION_KEY) || [])
  const winner = game.teams.A.score === game.teams.B.score ? 'Both teams' : game.teams.A.score > game.teams.B.score ? game.teams.A.name : game.teams.B.name
  const facts = ['Work can support another person’s work.', 'Some important contributions are less visible.', 'A stopped contribution can affect a whole community.', 'Skills and cooperation help communities function.']
  useEffect(() => { writeStored(REFLECTION_KEY, reflection); writeStored(REPORT_KEY, { completedAt: new Date().toISOString(), game, reflection }) }, [game, reflection])
  return <main className="results-screen"><section className="results-hero"><div className="confetti" aria-hidden="true">✦ ◆ ♥ ⛓ ✦</div><p className="eyebrow">Community contribution report</p><h1>You connected the <em>community.</em></h1><p>Different kinds of work help people, families and communities function.</p><div className="winner-callout"><span aria-hidden="true">🏆</span><div><small>Today’s community builders</small><b>{winner}</b></div></div></section><section className="report-grid"><article className="score-report"><h2>Total score</h2><div><span>{game.teams.A.name}</span><b>{game.teams.A.score}</b></div><div><span>{game.teams.B.name}</span><b>{game.teams.B.score}</b></div><TokenLegend /></article><article className="discovery-report"><h2>You discovered</h2><div className="stat-grid"><p><b>{game.discoveredWork.length}</b><span>types of work</span></p><p><b>{game.completedChallenges.length}</b><span>community connections</span></p><p><b>{game.completedChains}</b><span>work chains</span></p><p><b>{game.predictions}</b><span>predictions made</span></p><p><b>{game.problemsSolved}</b><span>problems solved</span></p><p><b>{game.hiddenWorkDiscovered}</b><span>hidden work noticed</span></p></div></article></section><section className="evidence-report"><h2>Learning evidence</h2><div>{game.discoveredWork.map(item => <span key={item}>{item}</span>)}</div>{game.recognitions.length > 0 && <><h3>Recognitions earned</h3><div>{game.recognitions.map(item => <span className="recognition-chip" key={item}>★ {item}</span>)}</div></>}</section><section className="reflection-card"><p className="eyebrow">Reflect together</p><h2>What will you carry forward?</h2><p>Select the ideas your team can now explain with an example.</p><div className="reflection-choices">{facts.map(fact => <button type="button" className={reflection.includes(fact) ? 'selected' : ''} onClick={() => setReflection(current => current.includes(fact) ? current.filter(item => item !== fact) : [...current, fact])} key={fact}>{reflection.includes(fact) ? '✓ ' : ''}{fact}</button>)}</div><p className="final-message">Every contribution can make a difference.</p><div className="results-actions"><button type="button" className="secondary-action" onClick={() => window.print()}>Print report</button><button type="button" className="primary-action large" onClick={onNew}>Play a new challenge <span aria-hidden="true">↻</span></button></div></section></main>
}

export default function App() {
  const [game, setGame] = useState<GameState>(() => newGame({ ...defaultSettings, ...(readStored<GameSettings>(SETTINGS_KEY) || {}) }))
  const [hasSaved, setHasSaved] = useState(() => Boolean(readStored<GameState>(GAME_KEY)))
  useEffect(() => { writeStored(SETTINGS_KEY, game.settings) }, [game.settings])
  useEffect(() => { if (game.screen === 'game') { writeStored(GAME_KEY, game); setHasSaved(true) } }, [game])
  const beginSetup = () => setGame(current => ({ ...newGame(current.settings, current.mode, current.sessionLength, [current.teams.A.name, current.teams.B.name]), screen: 'setup' }))
  const beginGame = () => setGame(current => ({ ...newGame(current.settings, current.mode, current.sessionLength, [current.teams.A.name || 'Team A', current.teams.B.name || 'Team B']), screen: 'game' }))
  const continueGame = () => { const saved = readStored<GameState>(GAME_KEY); if (saved) setGame({ ...normalizeGame(saved), screen: 'game' }) }
  const results = () => { removeStored(GAME_KEY); setHasSaved(false); setGame(current => ({ ...current, screen: 'results' })) }
  if (game.screen === 'setup') return <Setup game={game} setGame={setGame} onStart={beginGame} />
  if (game.screen === 'game') return <GameView game={game} setGame={setGame} onResults={results} />
  if (game.screen === 'results') return <Results game={game} onNew={beginSetup} />
  return <Home onNew={beginSetup} onContinue={continueGame} hasSaved={hasSaved} />
}
